services:
  http-server-projeto-korp:
    build:
      context: .
      dockerfile: Dockerfile
    image: http-server-projeto-korp:dev
    container_name: http-server-projeto-korp

    expose:
      - "8080"

    networks:
      - korp-backend

    restart: unless-stopped

    security_opt:
      - no-new-privileges:true

    read_only: true

    cap_drop:
      - ALL

  nginx:
    image: nginx:stable-alpine
    container_name: korp-nginx

    depends_on:
      - http-server-projeto-korp

    ports:
      - "80:80"

    volumes:
      - ./nginx/http-server-projeto-korp.conf:/etc/nginx/conf.d/default.conf:ro

    networks:
      - korp-backend

    restart: unless-stopped

    security_opt:
      - no-new-privileges:true

  prometheus:
    image: prom/prometheus:v3.14.0
    container_name: korp-prometheus

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus

    ports:
      - "9090:9090"

    networks:
      - korp-backend

    depends_on:
      - http-server-projeto-korp

    restart: unless-stopped

    security_opt:
      - no-new-privileges:true

networks:
  korp-backend:
    driver: bridge

volumes:
  prometheus-data:
